In [5]:
import numpy as np
np.tan(90)

-1.995200412208242

In [6]:
np.arcsin(90)

<ipython-input-6-83f060775ee7>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(90)


nan

In [7]:
np.arcsin(1)

1.5707963267948966

In [10]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a.max()

9

In [15]:
# Finding max element index
a.argmax()

8

In [18]:
s = np.array(np.random.randint(10,20,[4,4]))
s

array([[15, 13, 15, 19],
       [12, 13, 13, 10],
       [11, 11, 14, 16],
       [13, 19, 17, 17]])

In [20]:
ss = np.array(np.random.randint(1,10,[4,4]))
ss

array([[7, 3, 5, 1],
       [9, 7, 3, 7],
       [6, 8, 9, 2],
       [8, 5, 1, 1]])

In [22]:
np.vstack((s,ss))

array([[15, 13, 15, 19],
       [12, 13, 13, 10],
       [11, 11, 14, 16],
       [13, 19, 17, 17],
       [ 7,  3,  5,  1],
       [ 9,  7,  3,  7],
       [ 6,  8,  9,  2],
       [ 8,  5,  1,  1]])

In [23]:
np.hstack((s,ss))

array([[15, 13, 15, 19,  7,  3,  5,  1],
       [12, 13, 13, 10,  9,  7,  3,  7],
       [11, 11, 14, 16,  6,  8,  9,  2],
       [13, 19, 17, 17,  8,  5,  1,  1]])

In [24]:
np.column_stack((s,ss))

array([[15, 13, 15, 19,  7,  3,  5,  1],
       [12, 13, 13, 10,  9,  7,  3,  7],
       [11, 11, 14, 16,  6,  8,  9,  2],
       [13, 19, 17, 17,  8,  5,  1,  1]])

In [25]:
s+ss

array([[22, 16, 20, 20],
       [21, 20, 16, 17],
       [17, 19, 23, 18],
       [21, 24, 18, 18]])

In [26]:
s*ss

array([[105,  39,  75,  19],
       [108,  91,  39,  70],
       [ 66,  88, 126,  32],
       [104,  95,  17,  17]])

In [27]:
s@ss

array([[464, 351, 268, 155],
       [359, 281, 226, 139],
       [388, 302, 230, 132],
       [500, 393, 292, 197]])

In [28]:
s.dot(ss)

array([[464, 351, 268, 155],
       [359, 281, 226, 139],
       [388, 302, 230, 132],
       [500, 393, 292, 197]])

In [29]:
s.transpose()

array([[15, 12, 11, 13],
       [13, 13, 11, 19],
       [15, 13, 14, 17],
       [19, 10, 16, 17]])

In [31]:
s.trace()

59

In [35]:
np.hsplit(s,2)

[array([[15, 13],
        [12, 13],
        [11, 11],
        [13, 19]]),
 array([[15, 19],
        [13, 10],
        [14, 16],
        [17, 17]])]

In [36]:
np.hsplit(s,[2,2])

[array([[15, 13],
        [12, 13],
        [11, 11],
        [13, 19]]),
 array([], shape=(4, 0), dtype=int32),
 array([[15, 19],
        [13, 10],
        [14, 16],
        [17, 17]])]

In [40]:
help(np.hsplit)

Help on function hsplit in module numpy:

hsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays horizontally (column-wise).
    
    Please refer to the `split` documentation.  `hsplit` is equivalent
    to `split` with ``axis=1``, the array is always split along the second
    axis regardless of the array dimension.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[ 0.,   1.,   2.,   3.],
           [ 4.,   5.,   6.,   7.],
           [ 8.,   9.,  10.,  11.],
           [12.,  13.,  14.,  15.]])
    >>> np.hsplit(x, 2)
    [array([[  0.,   1.],
           [  4.,   5.],
           [  8.,   9.],
           [12.,  13.]]),
     array([[  2.,   3.],
           [  6.,   7.],
           [10.,  11.],
           [14.,  15.]])]
    >>> np.hsplit(x, np.array([3, 6]))
    [array([[ 0.,   1.,   2.],
           [ 4.,   5.,   6.],
     

In [41]:
np.vsplit(s,[2,2])

[array([[15, 13, 15, 19],
        [12, 13, 13, 10]]),
 array([], shape=(0, 4), dtype=int32),
 array([[11, 11, 14, 16],
        [13, 19, 17, 17]])]

In [44]:
np.round(9.7)

10.0