# H1 tag
## H2 tag
### H3 tag
#### H4 tag
##### H5 tag
###### H6 tag

In [3]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [4]:
len(dir(np))

620

In [7]:
d1 = np.array([45,33,49,45,50,29])
d1

array([45, 33, 49, 45, 50, 29])

In [11]:
d1.shape
d1.size
d1.ndim
d1

array([45, 33, 49, 45, 50, 29])

In [13]:
d1[1]

33

In [25]:
d2 = np.array(['ea',3,4.7,True])
len(d2)

4

In [27]:
import time
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname']

In [30]:
st = time.time()
l = [x for x in range(1,100000)]
ll = [ x for x in range(1,100000)]
o = list(map(lambda x,y : x*y, l,ll))
et = time.time()
et-st

0.05207014083862305

In [32]:
st = time.time()
a1 = np.array(l)
a2 = np.array(ll)
a1*a2
et = time.time()
et-st

0.027956724166870117

In [61]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2
a2[:,2].max()

9

In [60]:
a2[:,2].max()
sum(a2)
#a2.sum(axis = 0)

array([12, 15, 18])

In [66]:
d3 = np.array([[[1,2,3],[12,3,4]],[[12,33,44],[12,11,23]],[[10,29,19],[11,233,455]]])
d3.ndim

3

In [72]:
d3[0,0,1]

2

## Arrange()

In [90]:
for i in range(1,5):
    print(i,end=' ')

1 2 3 4 

In [79]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1,5,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75])

In [95]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [107]:
# Zeros matrix
np.zeros([2,5])
np.ones([2,5])
np.eye(5,5)
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [112]:
marks = np.array([[1,4,3,2,2],[2,3,412,34,2]])
ad = np.tile(5,[2,5])
marks = marks + ad
marks

array([[  6,   9,   8,   7,   7],
       [  7,   8, 417,  39,   7]])

In [115]:
m = np.array([[1,192,299],[3,282,2],[292,393,29]])
np.linalg.inv(m)

array([[-3.05890389e-04, -4.63217860e-03,  3.47329598e-03],
       [-2.05664939e-05,  3.61171635e-03, -3.70362416e-05],
       [ 3.35871123e-03, -2.30373699e-03,  1.21660950e-05]])

In [116]:
np.linalg.eig(m)

(array([-280.61552412,  337.32207606,  255.29344806]),
 array([[ 0.72841569, -0.683043  ,  0.71182342],
        [-0.00144855, -0.06334508, -0.13162684],
        [-0.68513392, -0.72762604,  0.68991433]]))

### Random

In [154]:
np.random.random(10)
# np.random.rand(10)
np.random.randint(10,20,30)

array([18, 11, 16, 17, 18, 19, 10, 11, 14, 15, 11, 16, 10, 13, 13, 10, 14,
       14, 17, 11, 11, 15, 11, 11, 17, 10, 16, 10, 14, 19])

In [150]:
np.random.randint(10,20,[4,6])

array([[10, 13, 13, 13, 11, 13],
       [18, 12, 10, 19, 17, 14],
       [14, 17, 18, 18, 18, 12],
       [15, 14, 15, 19, 11, 10]])

In [155]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [156]:
np.arange(1,49).reshape(3,4,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])